---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.0
#  - name: ubuntu-15.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[ndb::memcached]
      - recipe[ndb::bench]
    attributes:
         ndb:
            user: mysql
            group: mysql
            dir: "/tmp"
            DataMemory: "111"
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            mysql_port: 3399
            mysql_socket: /tmp/mysql-alt.sock
         kagent:
            enabled: "false"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
